apiVersion: v1
data:
  gitlab.rb: |-
    external_url 'http://192.168.223.8:30080'
    gitlab_rails['initial_root_password'] = "root1234"
    gitlab_rails['db_adapter'] = "postgresql"
    gitlab_rails['db_encoding'] = "utf8"
    gitlab_rails['db_collation'] = nil
    gitlab_rails['db_database'] = "gitlab"
    gitlab_rails['db_pool'] = 1
    gitlab_rails['db_username'] = "root"
    gitlab_rails['db_password'] = "123456"
    gitlab_rails['db_host'] = "postgres"
    gitlab_rails['db_port'] = 5432
    gitlab_rails['db_sslcompression'] = 0
    gitlab_rails['db_sslrootcert'] = nil
    gitlab_rails['db_prepared_statements'] = false
    gitlab_rails['db_statements_limit'] = 1000
    gitlab_rails['redis_host'] = "redis"
    gitlab_rails['redis_port'] = 6379
    gitlab_rails['redis_ssl'] = false
    gitlab_rails['redis_password'] = nil
    gitlab_rails['redis_database'] = 0
    gitlab_rails['gitlab_shell_ssh_port'] = 30022
    nginx['listen_port'] = 30080
    nginx['listen_https'] = false
kind: ConfigMap
metadata: 
  name: gitlab-configmap
  namespace: devops
